class fac {
	name = "FAC";
	description = "Big bada boom";
	traits[] = {
		{"UAVHacker",true}
	};
	customVariables[] = {
		{"YMF_iscom", true, true},
		{"draWhitelisted",TRUE,TRUE},
		{"TFAR_freq_sr",{"100.1","110","120","33","100","75","60","35"},true}
	};
    
	icon = "a3\ui_f\data\map\vehicleicons\iconmanexplosive_ca.paa";

	defaultLoadout[] = {
            {"SPS_hk417_13_afg_ral8000_f","","rhsusf_acc_anpeq16a","sps_vortex_spitfire_gen2_x5_RMR_tan",{"SPS_20Rnd_762x51mm_M80A1_EPR",20},{},""},{},
			{"sps_hk_vp9_stnd_black","","","",{"16Rnd_9x21_Mag",17},{},""},
			{"U_tweed_acu_summer_ocp_tuck_jedi",{{"rhs_mag_m67",2,1}}},{"V_tweed_iotv_mk4_cell_45_1",{{"ItemcTabHCam",1},{"16Rnd_9x21_Mag",3,17},{"SPS_20Rnd_762x51mm_M80A1_EPR",12,20}}},
			{"B_simc_US_Molle_sturm_OCP_RTO_wasser",{{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ItemcTabMisc",1},{"ACE_IR_Strobe_Item",1},{"B_IR_Grenade",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"kat_IFAK",1},{"ACE_EarPlugs",2},{"ACE_CableTie",5},{"kat_gasmaskFilter",2},{"kat_mask_M50",1},{"ACE_MapTools",1},{"ACE_PlottingBoard",1},{"ACE_RangeCard",1},{"ACE_artilleryTable",1},{"psq42_blk",1},{"acex_intelitems_notepad",1,1},{"Chemlight_blue",2,1},{"Chemlight_green",2,1},{"SmokeShellRed",3,1},{"SmokeShellGreen",3,1},{"SmokeShell",2,1},{"SmokeShellBlue",2,1}}},"H_tweed_ihps_g_tasc_rail","G_oak_1_cut",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
			{"ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch",""}
    };
	arsenalitems[] = {
		"SPS_hk337_afg_fde_f",
        "SPS_hk337_afg_ral8000_f",
        "SPS_hk337_black_f",
        "SPS_hk337_fde_f",
        "SPS_hk337_hk_ctr_afg_black_f",
        "SPS_hk337_hk_ctr_afg_fde_f",
        "SPS_hk337_hk_ctr_afg_ral8000_f",
        "SPS_hk337_hk_ctr_black_f",
        "SPS_hk337_hk_ctr_fde_f",
        "SPS_hk337_hk_ctr_ral8000_f",
        "SPS_hk337_hk_ctr_vfg_black_f",
        "SPS_hk337_hk_ctr_vfg_fde_f",
        "SPS_hk337_hk_ctr_vfg_ral8000_f",
        "SPS_hk337_ral8000_f",
        "SPS_hk337_t_afg_black_f",
        "SPS_hk337_t_afg_fde_f",
        "SPS_hk337_t_afg_ral8000_f",
        "SPS_hk337_t_black_f",
        "SPS_hk337_t_ctr_afg_black_f",
        "SPS_hk337_t_ctr_afg_fde_f",
        "SPS_hk337_t_ctr_afg_ral8000_f",
        "SPS_hk337_t_ctr_black_f",
        "SPS_hk337_t_ctr_fde_f",
        "SPS_hk337_t_ctr_ral8000_f",
        "SPS_hk337_t_ctr_vfg_black_f",
        "SPS_hk337_t_ctr_vfg_fde_f",
        "SPS_hk337_t_ctr_vfg_ral8000_f",
        "SPS_hk337_t_fde_f",
        "SPS_hk337_t_ral8000_f",
        "SPS_hk337_t_vfg_black_f",
        "SPS_hk337_t_vfg_fde_f",
        "SPS_hk337_t_vfg_ral8000_f",
        "SPS_hk337_vfg_black_f",
        "SPS_hk337_vfg_fde_f",
        "SPS_hk337_vfg_ral8000_f",
		"rhsusf_hgu56p_black",
        "rhsusf_hgu56p_green",
        "rhsusf_hgu56p_mask_black_skull",
        "rhsusf_hgu56p_mask_black",
        "rhsusf_hgu56p_mask_green_mo",
        "rhsusf_hgu56p_mask_green",
        "rhsusf_hgu56p_mask_mo",
        "rhsusf_hgu56p_mask_pink",
        "rhsusf_hgu56p_mask_saf",
        "rhsusf_hgu56p_mask_skull",
        "rhsusf_hgu56p_mask_smiley",
        "rhsusf_hgu56p_mask_tan",
        "rhsusf_hgu56p_mask",
        "rhsusf_hgu56p_pink",
        "rhsusf_hgu56p_saf",
        "rhsusf_hgu56p_tan",
        "rhsusf_hgu56p_usa",
        "rhsusf_hgu56p_visor_black",
        "rhsusf_hgu56p_visor_green",
        "rhsusf_hgu56p_visor_mask_black_skull",
        "rhsusf_hgu56p_visor_mask_black",
        "rhsusf_hgu56p_visor_mask_Empire_black",
        "rhsusf_hgu56p_visor_mask_green_mo",
        "rhsusf_hgu56p_visor_mask_green",
        "rhsusf_hgu56p_visor_mask_mo",
        "rhsusf_hgu56p_visor_mask_pink",
        "rhsusf_hgu56p_visor_mask_saf",
        "rhsusf_hgu56p_visor_mask_skull",
        "rhsusf_hgu56p_visor_mask_smiley",
        "rhsusf_hgu56p_visor_mask_tan",
        "rhsusf_hgu56p_visor_mask",
        "rhsusf_hgu56p_visor_pink",
        "rhsusf_hgu56p_visor_saf",
        "rhsusf_hgu56p_visor_tan",
        "rhsusf_hgu56p_visor_usa",
        "rhsusf_hgu56p_visor_white",
        "rhsusf_hgu56p_visor",
        "rhsusf_hgu56p_white",
        "rhsusf_hgu56p",
		"B_simc_US_Molle_sturm_OCP_RTO_wasser",
		"B_simc_US_Molle_sturm_OCP_RTO",
		"ACE_artilleryTable",
		"ACE_PlottingBoard",
		"acex_intelitems_notepad",
		"B_UavTerminal",
		"ItemcTabMisc",
		"ACE_RangeCard",
		"lxim_vs17_vs17"
	};
};