class teamlead12 {
    name = "Team Leader";
    description = "The one who is to blame";
    traits[] = {};
    customVariables[] = {
        {"TFAR_freq_sr",{"100.1","110","110.2","33","100","75","60","35"},true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanleader_red.paa";

    defaultLoadout[] = {
            {"lxim_sig_XM7","KAR_XM250_SUP","CUP_acc_ANPEQ_15","lxim_equipment_optic_DMS",{"lxim_sig_25Rnd_Fury",25},{},""},{},
            {"CUP_hgun_M17_Black","","","",{"CUP_17Rnd_9x19_M17_Black",17},{},""},
            {"U_tweed_acu_summer_ocp",{{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"kat_IFAK",1},{"ACE_fieldDressing",4},{"ACE_tourniquet",4},{"kat_Painkiller",1,4}}},
            {"V_tweed_msv_mk2_1",{{"CUP_17Rnd_9x19_M17_Black",3,17},{"ACE_CableTie",4},{"SmokeShell",2,1},{"ACE_microDAGR",1},{"ACE_Flashlight_MX991",1},{"HandGrenade",2,1},{"lxim_sig_25Rnd_Fury",12,25}}},
            {"lxim_backpack_Backpack_Kitbag_Medic_RGR",{{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ACE_IR_Strobe_Item",1},{"B_IR_Grenade",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"ACE_EarPlugs",2},{"ACE_CableTie",5},{"psq42_blk",1}}},
            "H_tweed_ihps_g_tasc_rail","CUP_TK_NeckScarf",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
            {"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}
    };
    arsenalitems[] = {
        "cup_glaunch_mk13",
        "CUP_FlareYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "uh60_jvmf_tablet",
        "lxim_vs17_vs17",
        // "ItemGPSMisc",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "CUP_sgun_M1014_Entry",
        "CUP_sgun_M1014_Entry_vfg"
    };
};
