class Dynamic_Roles {
    #include "outlaw_hq\config_co.hpp"
    #include "outlaw_hq\config_xo.hpp"
    #include "outlaw_hq\config_medic.hpp"
    #include "outlaw_hq\config_jtac.hpp"
    #include "outlaw_hq\config_engineer.hpp"
    #include "outlaw_hq\config_mark.hpp"

    #include "thunder\config_cmd.hpp"
    #include "thunder\config_driver.hpp"
    #include "thunder\config_gunner.hpp"
    #include "thunder\config_medic.hpp"

    #include "outlaw_1_1\config_engineer.hpp"
    #include "outlaw_1_1\config_squadleader.hpp"
    #include "outlaw_1_1\config_teamleader.hpp"
    #include "outlaw_1_1\config_medic.hpp"
    #include "outlaw_1_1\config_jtac.hpp"
    #include "outlaw_1_1\config_dismount.hpp"
    #include "outlaw_1_1\config_marksman.hpp"
    #include "outlaw_1_1\config_grenadier.hpp"
    #include "outlaw_1_1\config_machine.hpp"
    #include "outlaw_1_1\config_heavyat.hpp"

    #include "outlaw_1_2\config_engineer.hpp"
    #include "outlaw_1_2\config_squadleader.hpp"
    #include "outlaw_1_2\config_teamleader.hpp"
    #include "outlaw_1_2\config_medic.hpp"
    #include "outlaw_1_2\config_jtac.hpp"
    #include "outlaw_1_2\config_dismount.hpp"
    #include "outlaw_1_2\config_marksman.hpp"
    #include "outlaw_1_2\config_grenadier.hpp"
    #include "outlaw_1_2\config_machine.hpp"
    #include "outlaw_1_2\config_heavyat.hpp"

    #include "outlaw_1_3\config_engineer.hpp"
    #include "outlaw_1_3\config_squadleader.hpp"
    #include "outlaw_1_3\config_teamleader.hpp"
    #include "outlaw_1_3\config_medic.hpp"
    #include "outlaw_1_3\config_jtac.hpp"
    #include "outlaw_1_3\config_dismount.hpp"
    #include "outlaw_1_3\config_marksman.hpp"
    #include "outlaw_1_3\config_grenadier.hpp"
    #include "outlaw_1_3\config_machine.hpp"
    #include "outlaw_1_3\config_heavyat.hpp"

    #include "rhino\config_squadleader.hpp"
    #include "rhino\config_engineer.hpp"
    #include "rhino\config_savior.hpp"

    #include "phoenix\config_pilot.hpp"
    #include "phoenix\config_crewchief.hpp"
    #include "phoenix\config_medic.hpp"
    #include "phoenix\config_jtac.hpp"

    #include "training\config_cadre.hpp"
    #include "training\config_dismount.hpp"
    #include "training\config_engineer.hpp"
    #include "training\config_jtac.hpp"
    #include "training\config_medic.hpp"
    #include "training\config_zeus.hpp"

};
