// this is a list of approved/known mods which are allowed on LXIF servers
// this is only used for logging and is not an actual restriction on what mods can be loaded
private _approvedMods = [	
    "@3CB BAF Units (ACE compatibility)",
    "@3CB BAF Units",
    "@Enhanced Soundscape",
    "@Gruppe Adler Trenches",
    "@Enhanced Movement Rework",
    "@BettIR (Legacy v0.2.1)",
    "@ACE Compats - RHS Compats",
    "@3den Enhanced",
    "@Zeus Enhanced - ACE3 Compatibility",
    "@NIArms All in One- ACE Compatibility",
    "@3CB BAF Weapons (RHS ammo compatibility)",
    "@cTab",
    "@3CB Factions",
    "@DUI - Squad Radar",
    "@ACE 3 Extension (Placeables)",
    "@NIArms All in One - RHS Compatibility",
    "@ACRE Animations",
    "@Tier 1 Artillery Mod",
    "@JSRS SOUNDMOD - RHS  AiO Mod Pack Sound Support",
    "@ADF Vanilla - Arma 3 Vanilla Re-Texture to Australian Defence Force FICTIONAL",
    "@Special Stealth Uniforms [SSU]",
    "@Project OPFOR",
    "@NIArms All In One (V14 Onwards)",
    "@ace",
    "@Zeus Enhanced",
    "@ACRE2",
    "@RHSSAF",
    "@CUP Terrains - Maps",
    "@Simple MapTools",
    "@Medium Utility Helicopters",
    "@CUP Terrains - Core",
    "@JSRS SOUNDMOD",
    "@Enhanced Movement",
    "@RHSGREF",
    "@3CB BAF Equipment",
    "@3CB BAF Weapons",
    "@3CB BAF Vehicles",
    "@RKSL Studios - Attachments v3.02",
    "@RHSAFRF",
    "@RHSUSAF",
    "@CBA_A3",
    "@ACRE2 S.O.G. Prairie Fire Compatibility",
    "@FOW ACRE2 Compatibility",
    "@Iron Front ArmA 3 - Faces of War Compatibility patch",
    "@Faces of War",
    "@Ravage",
    "@Half-Life 2 - Echoes of the Resonance Cascade",
    "@Operation TREBUCHET First Contact ACE Compat",
    "@Drongos Spooks and Anomalies",
    "@Operation TREBUCHET First Contact",
    "@Operation TREBUCHET ACE Compat",
    "@Operation TREBUCHET",
    "@ALiVE",
    "@HBQ_SpawnSystem",
    "@ALiVE - Battlefield Manager",
    "@Lxifs of Battle Custom",
    "@Interiors for CUP",
    "@Metis Marker",
    "@SIT 1erGTD",
    "@GRAD Civilians",
    "@Breach",
    "@Simplex Support Services [DEV BUILD]",
    "@Arma 3 Athena",
    "@A3 Iranian Commandos 2035",
    "@Task Force Arrowhead Radio (BETA!!!)",
    "@Foxtrot Paramilitary Gear Pack v2",
    "@SPS Equipment",
    "@SPS Weapons V2",
    "@Arma 3 Atlas",
    "@ACE3 Arsenal Extended - Core",
    "@Arma 3 Aegis",
    "@Arma 3 Atlas - Opposing Forces",
    "@cTab 1erGTD",
    "@Community Factions Project (CFP)",
    "@W28",
    "@Better Inventory",
    "@Commander Turret Override",
    "@Crows Zeus Additions",
    "@CUP Units",
    "@CUP Vehicles",
    "@CUP Weapons",
    "@Fire Support Plus",
    "@MAAWS Additional Ammo Types",
    "@ZEC - Zeus and Eden Templates - Building Compositions",
    "@ZECCUP - Zeus and Eden Templates for CUP Terrains",
    "@ZEI - Zeus and Eden Interiors",
    "@Zeus Immersion Sounds",
    "@Dagger Island Training Complex"
];