class teamleadpsf {
    name = "Team Leader";
    description = "The SGT hates me";
    traits[] = {};
    customVariables[] = {
        {"TFAR_freq_sr",{"100.1","110","110.2","33","100","75","60","35"},true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanleader_red.paa";

    defaultLoadout[] = {
            {"cup_arifle_hk416_wood","CUP_muzzle_snds_G36_wood","","CUP_optic_Elcan_reflex_OD",{"CUP_30Rnd_556x45_Emag",30},{},""},{},
            {"CUP_hgun_M9A1","CUP_muzzle_snds_M9","CUP_acc_Glock17_Flashlight","",{"CUP_15Rnd_9x19_M9",15},{},""},
            {"U_I_CombatUniform",{{"ACE_EarPlugs",2},{"ACE_CableTie",4},{"ACE_IR_Strobe_Item",1},{"ACE_SpraypaintGreen",1},{"ace_marker_flags_green",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ACE_Clacker",1},{"ACE_DefusalKit",1}}},
            {"V_CarrierRigKBT_01_light_Olive_F",{{"CUP_30Rnd_556x45_Emag",11,30},{"CUP_15Rnd_9x19_M9",3,15},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",1,1}}},
            {"lxim_backpack_TacticalPack_Multicam_Woodland",{{"kat_AFAK",1},{"tsp_breach_block_mag",4,1},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1}}},
            "CUP_H_OpsCore_Covered_AAF_SF","",{"Binocular","","","",{},{},""},
            {"ItemMap","ItemMicroDAGR","TFAR_anprc152","ItemCompass","ItemWatch","CUP_NVG_GPNVG_green"}
    };
    arsenalitems[] = {
        "cup_glaunch_mk13",
        "CUP_FlareYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "uh60_jvmf_tablet",
        "lxim_vs17_vs17",
        // "ItemGPSMisc",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "CUP_sgun_M1014_Entry",
        "CUP_sgun_M1014_Entry_vfg"
    };
};
