class medic12 {
    name = "medic";
    description = "MEDIC!";
    traits[] = {
        {"Medic",true}
    };
    customVariables[] = {
        {"ace_medical_medicClass",2,true},
        {"YMF_ismed", true, true},
        {"TFAR_freq_sr",{"100.1","120","120.1","33","100","75","60","35"},true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanmedic_green.paa";

    defaultLoadout[] = {
            {"lxim_sig_XM7","KAR_XM250_SUP","CUP_acc_ANPEQ_15","lxim_equipment_optic_DMS",{"lxim_sig_25Rnd_Fury",25},{},""},{},
            {"CUP_hgun_M17_Coyote","","CUP_acc_Glock17_Flashlight","",{"CUP_21Rnd_9x19_M17_Coyote",21},{},""},
            {"U_tweed_acu_summer_ocp",{{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"kat_IFAK",1},{"ACE_fieldDressing",4},{"ACE_tourniquet",4},{"kat_Painkiller",1,4}}},
            {"V_tweed_msv_mk2_1",{{"CUP_17Rnd_9x19_M17_Black",3,17},{"ACE_CableTie",4},{"SmokeShell",2,1},{"ACE_microDAGR",1},{"ACE_Flashlight_MX991",1},{"HandGrenade",2,1},{"lxim_sig_25Rnd_Fury",12,25}}},
            {"B_simc_US_Molle_sturm_OCP_thermos_od7",{{"ACE_IR_Strobe_Item",1},{"B_IR_Grenade",1},{"ACE_tourniquet",4},{"ACE_splint",4},{"ACE_elasticBandage",40},{"psq42_blk",1},{"ACE_packingBandage",20},{"ACE_salineIV",4},{"ACE_salineIV_500",10},{"ACE_epinephrine",14},{"ACE_adenosine",14},{"ACE_fieldDressing",24},{"ACE_quikclot",14},{"ACE_morphine",24},{"lxim_naloxone",14}}},
            "H_tweed_ihps_tasc_rail","G_tweed_ESS_Green",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
            {"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}
    };
    arsenalitems[] = {
        "kat_IV_16",
        "kat_aatKit",
        "kat_accuvac",
        "kat_AED",
        "kat_AFAK",
        "kat_amiodarone",
        "kat_atropine",
        "kat_Bubble_Wrap",
        "kat_BVM",
        "kat_Carbonate",
        "kat_chestSeal",
        "kat_clamp",
        "kat_coag_sense",
        "kat_crossPanel",
        "kat_EACA",
        "KAT_Empty_bloodIV_250",
        "KAT_Empty_bloodIV_500",
        "kat_epinephrineIV",
        "kat_etomidate",
        "kat_fentanyl",
        "kat_flumazenil",
        "kat_guedel",
        "kat_IO_FAST",
        "kat_IV_16",
        "kat_ketamine",
        "kat_larynx",
        "kat_lidocaine",
        "kat_lorazepam",
        "kat_MFAK",
        "kat_nalbuphine",
        "kat_naloxone",
        "kat_nasal",
        "kat_ncdKit",
        "kat_nitroglycerin",
        "kat_norepinephrine",
        "kat_oxygenTank_150",
        "kat_oxygenTank_300",
        "kat_Painkiller",
        "kat_Penthrox",
        "kat_phenylephrine",
        "kat_phenylephrineAuto",
        "kat_plate",
        "kat_pocketBVM",
        "kat_Pulseoximeter",
        "kat_reboa",
        "kat_retractor",
        "kat_scalpel",
        "kat_stethoscope",
        "kat_suction",
        "kat_TXA",
        "kat_ultrasound",
        "kat_vacuum",
        "ACE_surgicalKit",
        "kat_X_AED",
        "lxim_backpack_Backpack_Kitbag_Medic_Green",
        "lxim_backpack_Backpack_Kitbag_Medic_MTP",
        "lxim_backpack_Backpack_Kitbag_Medic_Coyote",
        "lxim_backpack_Backpack_Kitbag_Medic_Tan",
        "lxim_backpack_Backpack_Kitbag_Medic_RGR",
        "B_simc_US_Molle_sturm_OCP_RTO_wasser",
        "B_simc_US_Molle_sturm_OCP_RTO",
        "ACE_adenosine",
        "ACE_fieldDressing",
        "ACE_elasticBandage",
        "ACE_packingBandage",
        "ACE_splint",
        "ACE_quikclot",
        "lxim_backpack_Backpack_Kitbag_Medic_Black",
        "lxim_backpack_Backpack_Kitbag_Medic_Sage",
        "lxim_backpack_Backpack_Kitbag_Medic_White"
    };
};