class teamleadsf {
    name = "Team Leader";
    description = "The SGT hates me";
    traits[] = {};
    customVariables[] = {
        {"TFAR_freq_sr",{"100.1","110","110.2","33","100","75","60","35"},true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanleader_red.paa";

    defaultLoadout[] = {
            {"arifle_CTAR_blk_F","muzzle_snds_58_blk_F","CUP_acc_ANPEQ_15_Flashlight_OD_L","CUP_optic_AC11704_Black",{"30Rnd_580x42_Mag_F",30},{},""},{},
            {"CUP_hgun_M9","CUP_muzzle_snds_M9","","",{"CUP_15Rnd_9x19_M9",15},{},""},
            {"U_I_L_Uniform_01_deserter_F",{{"kat_AFAK",1},{"ACE_EarPlugs",2},{"ACE_CableTie",4},{"ACE_EntrenchingTool",1}}},
            {"V_PlateCarrier1_blk",{{"30Rnd_580x42_Mag_F",12,30},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",2,1}}},
            {"lxim_backpack_Carryall_Solid_Black",{{"ACE_Flashlight_MX991",1},{"ACE_IR_Strobe_Item",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"ACE_EarPlugs",2},{"ACE_CableTie",5},{"psq42_blk",1},{"ACE_Clacker",1},{"ACE_microDAGR",1},{"tsp_breach_block_mag",2,1}}},
            "CUP_H_OpsCore_Spray","G_Balaclava_TI_tna_F",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
            {"ItemMap","ItemGPS","TFAR_anprc152",
            "ItemCompass","ACE_Altimeter","CUP_NVG_GPNVG_green"}
    };
    arsenalitems[] = {
        "cup_glaunch_mk13",
        "CUP_FlareYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "uh60_jvmf_tablet",
        "lxim_vs17_vs17",
        // "ItemGPSMisc",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "CUP_sgun_M1014_Entry",
        "CUP_sgun_M1014_Entry_vfg"
    };
};
