class teamlead11 {
    name = "Team Leader";
    description = "The one who is to blame";
    traits[] = {};
    customVariables[] = {
        {"ace_medical_medicClass",0,true},
        {"ace_isEngineer",0,true},
        {"YMF_is11", true, true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanleader_red.paa";

    defaultLoadout[] = {
            {"lxim_sig_XM7","ICM_SLX_Suppressor_Arid_F","rhsusf_acc_anpeq15side","lxim_equipment_optic_DMS",{"lxim_sig_25Rnd_Fury",25},{},""},{"rhs_weap_M136","","","",{},{},""},
            {"MHS_M17","","MHS_X300U","MHS_RomeoM17",{"MHS_21rnd_9MM_124FMJ_M17",21},{},""},
            {"U_tweed_acu_summer_ocp",{{"ItemcTabMisc",1},{"ACE_EarPlugs",2},{"ACE_CableTie",5}}},
            {"V_tweed_iotv_mk4_cell_45_2",{{"ItemcTabHCam",1},{"lxim_sig_25Rnd_Fury",8,25},{"rhs_mag_m67",2,1},{"SmokeShellRed",3,1},{"SmokeShellGreen",3,1},{"SmokeShell",3,1}}},
            {"B_simc_US_Molle_sturm_OCP",{{"ACE_EntrenchingTool",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"psq42_blk",1},{"lxim_medbags_FirstAid",2},{"ACM_ChestSeal",2},{"ACM_SAMSplint",2},{"JCA_G_AirPurifyingRespirator_03_black_clear_F",1},{"ACE_SpraypaintBlue",1},{"ACE_IR_Strobe_Item",1}}},
            "H_tweed_ihps_g_tasc_rail","",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
            {"ItemMap","ItemAndroid","TFAR_anprc152_2","ItemCompass","ACE_Altimeter",""}
    };
    arsenalitems[] = {
        "1Rnd_HE_Grenade_shell",
        "ACE_HuntIR_M203",
        "ACE_LAMG_SpareBarrel",
        "ACE_LWAMG_SpareBarrel",
        "launch_MRAWS_green_F",
        "launch_MRAWS_olive_F",
        "launch_MRAWS_sand_F",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "lxim_vs17_vs17",
        "rhs_fgm148_magazine_AT",
        "rhs_fim92_mag",
        "rhs_mag_M397_HET",
        "rhs_mag_m4009",
        "rhs_mag_M433_HEDP",
        "rhs_mag_M441_HE",
        "rhs_mag_m576",
        "rhs_mag_M583A1_white",
        "rhs_mag_M585_white_cluster",
        "rhs_mag_m661_green",
        "rhs_mag_m662_red",
        "rhs_mag_M663_green_cluster",
        "rhs_mag_M664_red_cluster",
        "rhs_mag_m713_Red",
        "rhs_mag_m714_White",
        "rhs_mag_m715_Green",
        "rhs_mag_m716_yellow",
        "rhs_mag_maaws_HE",
        "rhs_mag_maaws_HEAT",
        "rhs_mag_maaws_HEDP",
        "rhs_weap_fgm148",
        "rhs_weap_fim92",
        "rhs_weap_m240B",
        "rhs_weap_m240G",
        "rhs_weap_M320",
        "rhsusf_acc_ARDEC_M240",
        "UGL_FlareGreen_F",
        "uh60_jvmf_tablet",
        "B_simc_US_Molle_sturm_OCP_RTO",
        "B_simc_US_Molle_sturm_OCP_RTO_wasser"
    };
};
