class squadleadcp {
    name = "Squad Leader";
    description = "The Chief hates me";
    traits[] = {};
    customVariables[] = {
        {"YMF_ismed", true, true},
        {"YMF_iscom", true, true},
        {"TFAR_freq_sr",{"100.1","110","110.1","33","100","75","60","35"},true}
    };
    icon = "\A3\ui_f\data\map\vehicleicons\iconmanofficer_ca.paa";

    defaultLoadout[] = {
            {"cup_arifle_g3a3_ris_vfg_black","","","CUP_optic_MicroT1_OD",{"CUP_20Rnd_762x51_G3",20},{},""},{},
            {"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},
            {"U_B_GEN_Soldier_F",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_CableTie",6},{"16Rnd_9x21_Mag",2,17},{"HandGrenade",1,1}}},
            {"V_TacVest_blk_POLICE",{{"CUP_30Rnd_545x39_AK74_plum_M",7,30},{"CUP_20Rnd_762x51_G3",3,20},{"CUP_15Rnd_9x19_M9",1,15}}},
            {"B_Messenger_Black_F",{{"kat_AFAK",1},{"ACE_CableTie",6},{"tsp_flashbang_m84",5,1},{"CUP_HandGrenade_M67",2,1},{"SmokeShell",3,1},{"ACE_Chemlight_HiYellow",3,1},{"ACE_Chemlight_HiWhite",3,1},{"ACE_Chemlight_HiRed",3,1},{"ACE_Chemlight_HiGreen",3,1},{"ACE_Chemlight_HiBlue",3,1},{"CUP_20Rnd_762x51_G3",3,20}}},
            "H_Cap_police","G_Bandanna_blk",{"Binocular","","","",{},{},""},
            {"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""}
    };
    arsenalitems[] = {
        "cup_glaunch_mk13",
        "CUP_FlareYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "CUP_FlareYellow_M203",
        "CUP_1Rnd_HE_M203",
        "CUP_1Rnd_HEDP_M203",
        "CUP_FlareRed_M203",
        "CUP_1Rnd_StarCluster_Green_M203",
        "CUP_1Rnd_StarCluster_Red_M203",
        "CUP_FlareWhite_M203",
        "CUP_1Rnd_Smoke_M203",
        "CUP_1Rnd_StarFlare_Red_M203",
        "CUP_FlareGreen_M203",
        "CUP_1Rnd_StarFlare_White_M203",
        "CUP_1Rnd_StarFlare_Green_M203",
        "CUP_1Rnd_SmokeGreen_M203",
        "ACE_HuntIR_M203",
        "CUP_1Rnd_StarCluster_White_M203",
        "CUP_1Rnd_SmokeRed_M203",
        "CUP_1Rnd_SmokeYellow_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "B_simc_US_Molle_sturm_OCP_RTO",
        "B_simc_US_Molle_sturm_OCP_RTO_wasser",
        "uh60_jvmf_tablet",
        "lxim_vs17_vs17",
        // "ItemGPSMisc",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "CUP_sgun_M1014_Entry",
        "CUP_sgun_M1014_Entry_vfg"
    };
};