class teamlead12 {
    name = "Team Leader";
    description = "The one who is to blame";
    traits[] = {};
    customVariables[] = {
        {"starting_152_channel", 3, true},
        {"starting_343_channel", 33, true}
    };
    icon = "z\LXIM\addons\media\images\Icons\iconmanleader_red.paa";

    defaultLoadout[] = {
            {"lxim_sig_XM7","KAR_XM250_SUP","rhsusf_acc_anpeq15","lxim_equipment_optic_DMS",{"lxim_sig_25Rnd_Fury",25},{},""},{},
            {"MHS_M17","","","",{"MHS_21rnd_9MM_124FMJ_M17",21},{},""},
            {"U_tweed_acu_summer_ocp",{{"ACE_EarPlugs",1},{"ItemcTabHCam",1},{"lxim_medbags_mopp",1},{"lxim_medbags_FirstAid",1},{"ACE_MapTools",1},{"ACRE_PRC148",1},{"ACRE_PRC152",1},{"",1,0}}},
            {"V_tweed_msv_mk2_1",{{"ACE_CableTie",4},{"ACE_microDAGR",1},{"ACE_Flashlight_MX991",1},{"MHS_21rnd_9MM_124FMJ_M17",3,21},{"SmokeShell",2,1},{"HandGrenade",2,1},{"lxim_sig_25Rnd_Fury",12,25}}},
            {"B_simc_US_Molle_sturm_OCP",{{"ACE_EntrenchingTool",1},{"MS_Strobe_Mag_1",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"ACE_CableTie",5},{"psq42_blk",1}}},
            "H_tweed_ihps_g_tasc_rail","G_oak_2_cut",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
            {"ItemMap","ItemAndroid","","ItemCompass","ACE_Altimeter",""}
    };
    arsenalitems[] = {
        "launch_MRAWS_olive_F",
        "launch_MRAWS_sand_F",
        "launch_MRAWS_green_F",
        "rhs_weap_M320",
        "UGL_FlareGreen_F",
        "rhs_mag_M583A1_white",
        "rhs_mag_m576",
        "rhs_mag_m4009",
        "rhs_mag_M433_HEDP",
        "rhs_mag_M397_HET",
        "rhs_mag_m662_red",
        "rhs_mag_M663_green_cluster",
        "rhs_mag_m714_White",
        "rhs_mag_M585_white_cluster",
        "rhs_mag_m715_Green",
        "rhs_mag_M664_red_cluster",
        "rhs_mag_m713_Red",
        "rhs_mag_m661_green",
        "1Rnd_HE_Grenade_shell",
        "rhs_mag_M441_HE",
        "rhs_mag_m716_yellow",
        "ACE_HuntIR_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "ACE_HuntIR_M203",
        "ACE_LWAMG_SpareBarrel",
        "ACE_LAMG_SpareBarrel",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "rhs_weap_M320",
        "UGL_FlareGreen_F",
        "rhs_mag_M583A1_white",
        "rhs_mag_m576",
        "rhs_mag_m4009",
        "rhs_mag_M433_HEDP",
        "rhs_mag_M397_HET",
        "rhs_mag_m662_red",
        "rhs_mag_M663_green_cluster",
        "rhs_mag_m714_White",
        "rhs_mag_M585_white_cluster",
        "rhs_mag_m715_Green",
        "rhs_mag_M664_red_cluster",
        "rhs_mag_m713_Red",
        "rhs_mag_m661_green",
        "1Rnd_HE_Grenade_shell",
        "rhs_mag_M441_HE",
        "rhs_mag_m716_yellow",
        "rhs_weap_m240G",
        "rhs_weap_m240B",
        "rhsusf_acc_ARDEC_M240",
        "rhs_weap_fgm148",
        "rhs_weap_fim92",
        "rhs_fgm148_magazine_AT",
        "rhs_mag_maaws_HEAT",
        "rhs_mag_maaws_HE",
        "rhs_fim92_mag",
        "rhs_mag_maaws_HEDP",
        "lxim_backpack_Carryall_Solid_White",
        "lxim_backpack_Carryall_Multicam",
        "lxim_backpack_Carryall_Solid_CoyoteBrown",
        "lxim_backpack_Carryall_Solid_Black",
        "lxim_backpack_Carryall_Multicam_Woodland",
        "lxim_backpack_Carryall_US_Tigerstripe",
        "lxim_backpack_Carryall_US_M81",
        "lxim_backpack_Carryall_US_DCU",
        "lxim_backpack_Carryall_Solid_Olive",
        "lxim_backpack_Carryall_Multicam_Snow",
        "lxim_backpack_Carryall_Solid_Ranger_Green",
        "lxim_backpack_Kitbag_Multicam_Woodland",
        "lxim_backpack_Kitbag_Multicam",
        "lxim_backpack_Kitbag_Solid_CoyoteBrown",
        "lxim_backpack_Kitbag_US_DCU",
        "lxim_backpack_Kitbag_US_M81",
        "lxim_backpack_Kitbag_Solid_Black",
        "lxim_backpack_Kitbag_Solid_Olive",
        "lxim_backpack_Kitbag_Multicam_Snow",
        "lxim_backpack_Kitbag_Solid_White",
        "lxim_backpack_Kitbag_US_Tigerstripe",
        "lxim_backpack_Kitbag_Solid_Ranger_Green",
        "uh60_jvmf_tablet",
        "lxim_vs17_vs17",
        // "ItemGPSMisc",
        "lxim_sig_M250",
        "lxim_sig_M250_BLK",
        "rhs_weap_m240G",
        "rhs_weap_m240B",
        "rhsusf_acc_ARDEC_M240"
    };
};
