class pilot {
        name = "Pilot";
        description = "Weeeeeeeeeeeee";
        traits[] = {};
        customVariables[] = {
                {"ace_medical_medicClass",0,true},
        {"ace_isEngineer",0,true}
        };
        icon = "\A3\ui_f\data\map\vehicleicons\iconmanofficer_ca.paa";

        defaultLoadout[] = {
                {"rhs_weap_m4a1_carryhandle_mstock","","rhsusf_acc_anpeq15side","rhsusf_acc_ACOG_USMC",{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",30},{},""},{},
                {"MHS_M17","","","",{"MHS_21rnd_9MM_124FMJ_M17",21},{},""},
                {"U_tweed_acu_summer_ocp",{{"ACE_EarPlugs",1},{"ItemcTabHCam",1},{"lxim_medbags_mopp",1},{"lxim_medbags_FirstAid",1},{"ACE_MapTools",1},{"",1,0}}},
                {"V_tweed_msv_mk2_1",{{"ACE_CableTie",4},{"ACE_microDAGR",1},{"ACE_Flashlight_MX991",1},{"MHS_21rnd_9MM_124FMJ_M17",3,21},{"SmokeShell",2,1},{"HandGrenade",2,1},{"ACE_30Rnd_556x45_Stanag_M995_AP_mag",14,30}}},
                {"B_simc_US_Molle_sturm_OCP_RTO_wasser",{{"ACE_EntrenchingTool",1},{"MS_Strobe_Mag_1",1},{"ACE_wirecutter",1},{"ACE_Fortify",1},{"ACE_CableTie",5},{"psq42_blk",1}}},
                "H_tweed_ihps_g_tasc_rail","G_oak_2_cut",{"lxim_equipment_Vector_Designator","","","",{"Laserbatteries",1},{},""},
                {"ItemMap","ItemAndroid","TFAR_anprc152_1","ItemCompass","ACE_Altimeter",""}
        };
        arsenalitems[] = {
                "rhsusf_hgu56p_black",
                "rhsusf_hgu56p_green",
                "rhsusf_hgu56p_mask_black_skull",
                "rhsusf_hgu56p_mask_black",
                "rhsusf_hgu56p_mask_green_mo",
                "rhsusf_hgu56p_mask_green",
                "rhsusf_hgu56p_mask_mo",
                "rhsusf_hgu56p_mask_pink",
                "rhsusf_hgu56p_mask_saf",
                "rhsusf_hgu56p_mask_skull",
                "rhsusf_hgu56p_mask_smiley",
                "rhsusf_hgu56p_mask_tan",
                "rhsusf_hgu56p_mask",
                "rhsusf_hgu56p_pink",
                "rhsusf_hgu56p_saf",
                "rhsusf_hgu56p_tan",
                "rhsusf_hgu56p_usa",
                "rhsusf_hgu56p_visor_black",
                "rhsusf_hgu56p_visor_green",
                "rhsusf_hgu56p_visor_mask_black_skull",
                "rhsusf_hgu56p_visor_mask_black",
                "rhsusf_hgu56p_visor_mask_Empire_black",
                "rhsusf_hgu56p_visor_mask_green_mo",
                "rhsusf_hgu56p_visor_mask_green",
                "rhsusf_hgu56p_visor_mask_mo",
                "rhsusf_hgu56p_visor_mask_pink",
                "rhsusf_hgu56p_visor_mask_saf",
                "rhsusf_hgu56p_visor_mask_skull",
                "rhsusf_hgu56p_visor_mask_smiley",
                "rhsusf_hgu56p_visor_mask_tan",
                "rhsusf_hgu56p_visor_mask",
                "rhsusf_hgu56p_visor_pink",
                "rhsusf_hgu56p_visor_saf",
                "rhsusf_hgu56p_visor_tan",
                "rhsusf_hgu56p_visor_usa",
                "rhsusf_hgu56p_visor_white",
                "rhsusf_hgu56p_visor",
                "rhsusf_hgu56p_white",
                "rhsusf_hgu56p",
                "H_PilotHelmetHeli_B",
                "H_CrewHelmetHeli_B",
                "FIR_HGU56P_Skull_Death",
                "FIR_HGU56P_Skull",
                "H_PilotHelmetHeli_I_E",
                "H_CrewHelmetHeli_I_E",
                "ACE_NVG_Wide_Black",
                "ACE_NVG_Wide_Black_WP",
                "B_simc_US_Molle_sturm_OCP_RTO",
                "B_simc_US_Molle_sturm_OCP_RTO_wasser",
                "U_I_pilotCoveralls",
                "U_B_HeliPilotCoveralls",
                "rhsusf_ihadss",
                "RHS_jetpilot_usaf",
                "rhs_weap_m4",
                "FIR_JHMCS_Type2",
                "FIR_JHMCS_II",
                "FIR_JHMCS",
                "FIR_Fighter_Pilot_JASDF_Nomex",
                "FIR_Fighter_Pilot_JASDF_Nomex2",
                "FIR_Fighter_Pilot_JASDF_Nomex3",
                "FIR_Fighter_Pilot_JASDF_Nomex4",
                "FIR_Fighter_Pilot_JASDF_Nomex5",
                "FIR_Fighter_Pilot_JASDF_Nomex6",
                "FIR_Fighter_Pilot_JASDF_Nomex7",
                "B_UavTerminal"
        };
};
